// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNetwork() {
  return window['go']['main']['App']['GetNetwork']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Hello(arg1) {
  return window['go']['main']['App']['Hello'](arg1);
}

export function SetNetwork(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNetwork'](arg1, arg2, arg3);
}

export function TriggerGate(arg1) {
  return window['go']['main']['App']['TriggerGate'](arg1);
}
