// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function GetNetwork():Promise<service.NetworkInfo>;

export function Greet(arg1:string):Promise<string>;

export function Hello(arg1:string):Promise<string>;

export function SetNetwork(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TriggerGate(arg1:string):Promise<string>;
